spring.application.name=YOURSERVICENAME

# Server configurations
server.port=YOURSERVERPORT

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/YOUR-DBNAME
spring.datasource.username=YOURUSERNAME
spring.datasource.password=YOURPASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none

# URL used by the InventoryServiceClient
inventory.service.url=http://localhost:8080/api/v1/inventory

